{
 "title": "Main",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "limit", "label": "limit", "query": "5, 10, Tout : 100000" }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "// Source 1 : Bucket \"Monitoring\" (mesure: pc)\r\nsrc1 = from(bucket: \"monitoring\")\r\n  |> range(start: -1m)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pc\" and r[\"_field\"] == \"cpu_percent\")\r\n  |> group(columns: [\"host\"])\r\n  |> last()\r\n\r\n// Source 2 : Bucket \"BucketMonitoring\" (mesure: cpu)\r\nsrc2 = from(bucket: \"BucketMonitoring\")\r\n  |> range(start: -1m)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\" and r[\"_field\"] == \"cpu_percent\")\r\n  |> group(columns: [\"host\"])\r\n  |> last()\r\n\r\n// Union des deux sources\r\nunion(tables: [src1, src2])\r\n  |> group()\r\n  |> sort(columns: [\"_value\"], desc: true)\r\n  |> limit(n: ${limit})"
    }
   ]
  },
  {
   "title": "OFF_TIME",
   "type": "stat",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "calcOffTime = (bkt, meas) => from(bucket: bkt)\r\n  |> range(start: -7d)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == meas and r[\"_field\"] == \"uptime_minutes\")\r\n  |> group(columns: [\"host\"])\r\n  |> last()\r\n  |> map(fn: (r) => ({\r\n    host: r.host,\r\n    last_seen: r._time \r\n  }))\r\n\r\n// Union des résultats des deux buckets\r\nunion(tables: [\r\n  calcOffTime(bkt: \"monitoring\", meas: \"pc\"),\r\n  calcOffTime(bkt: \"BucketMonitoring\", meas: \"system\")\r\n])\r\n  // --- CRUCIAL : On regroupe par host pour fusionner les deux buckets ---\r\n  |> group(columns: [\"host\"])\r\n  |> max(column: \"last_seen\") // On garde la date la plus récente entre les deux buckets\r\n  \r\n  // --- Calcul final après avoir choisi le bucket le plus récent ---\r\n  |> map(fn: (r) => ({\r\n    host: r.host,\r\n    minutes_ago: float(v: (uint(v: now()) - uint(v: r.last_seen)) / uint(v: 60000000000))\r\n  }))\r\n  \r\n  // --- Filtre final : Uniquement si le PC est absent des DEUX buckets depuis > 5 min ---\r\n  |> filter(fn: (r) => r.minutes_ago >= 5.0)\r\n  |> keep(columns: [\"host\", \"minutes_ago\"])\r\n  |> group()"
    }
   ]
  },
  {
   "title": "RAM ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "src1 = from(bucket: \"monitoring\")\r\n  |> range(start: -1m)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pc\" and r[\"_field\"] == \"memory_percent\")\r\n  |> group(columns: [\"host\"])\r\n  |> last()\r\n\r\nsrc2 = from(bucket: \"BucketMonitoring\")\r\n  |> range(start: -1m)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"memory\" and r[\"_field\"] == \"memory_percent\")\r\n  |> group(columns: [\"host\"])\r\n  |> last()\r\n\r\nunion(tables: [src1, src2])\r\n  |> group()\r\n  |> sort(columns: [\"_value\"], desc: true)\r\n  |> limit(n: ${limit})"
    }
   ]
  },
  {
   "title": "BYTES SENT",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "src1 = from(bucket: \"monitoring\")\r\n  |> range(start: -1m)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pc\" and r[\"_field\"] == \"bytes_sent\")\r\n  |> group(columns: [\"host\"])\r\n  |> last()\r\n\r\nsrc2 = from(bucket: \"BucketMonitoring\")\r\n  |> range(start: -1m)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"network\" and r[\"_field\"] == \"bytes_sent\")\r\n  |> group(columns: [\"host\"])\r\n  |> last()\r\n\r\nunion(tables: [src1, src2])\r\n  |> group()\r\n  |> sort(columns: [\"_value\"], desc: true)\r\n  |> limit(n: ${limit})"
    }
   ]
  },
  {
   "title": "UPDATES",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "query": "src1 = from(bucket: \"monitoring\")\r\n  |> range(start: -1m)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pc\" and r[\"_field\"] == \"pending_updates\")\r\n  |> group(columns: [\"host\"])\r\n  |> last()\r\n\r\nsrc2 = from(bucket: \"BucketMonitoring\")\r\n  |> range(start: -1m)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"updates\" and r[\"_field\"] == \"pending_updates\")\r\n  |> group(columns: [\"host\"])\r\n  |> last()\r\n\r\nunion(tables: [src1, src2])\r\n  |> group()\r\n  |> sort(columns: [\"_value\"], desc: true)\r\n  |> limit(n: ${limit})"
    }
   ]
  },
  {
   "title": "DISK ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "// Source 1\r\nsrc1 = from(bucket: \"monitoring\")\r\n  |> range(start: v.timeRangeStart)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pc\" and r[\"_field\"] == \"percent\")\r\n  |> last()\r\n  // MODIFICATION ICI : On retire \"r.host + ' - '\"\r\n  |> map(fn: (r) => ({ r with display_name: r.disk + \"://\" }))\r\n\r\n// Source 2\r\nsrc2 = from(bucket: \"BucketMonitoring\")\r\n  |> range(start: v.timeRangeStart)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"disk\" and r[\"_field\"] == \"percent\")\r\n  |> last()\r\n  // MODIFICATION ICI : On retire \"r.host + ' - '\"\r\n  |> map(fn: (r) => ({ r with display_name: r.mountpoint + \" (\" + r.device + \")\" }))\r\n\r\nunion(tables: [src1, src2])\r\n  |> group()\r\n  |> sort(columns: [\"_value\"], desc: true)\r\n  |> limit(n: int(v: \"${limit}\"))\r\n\r\n  |> keep(columns: [\"_time\", \"_value\", \"display_name\", \"host\"]) \r\n  |> rename(columns: {_value: \"Occupation (%)\", display_name: \"Détails\"})"
    }
   ]
  },
  {
   "title": "BYTES RECEIVE",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "src1 = from(bucket: \"monitoring\")\r\n  |> range(start: -1m)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pc\" and r[\"_field\"] == \"bytes_recv\")\r\n  |> group(columns: [\"host\"])\r\n  |> last()\r\n\r\nsrc2 = from(bucket: \"BucketMonitoring\")\r\n  |> range(start: -1m)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"network\" and r[\"_field\"] == \"bytes_recv\")\r\n  |> group(columns: [\"host\"])\r\n  |> last()\r\n\r\nunion(tables: [src1, src2])\r\n  |> group()\r\n  |> sort(columns: [\"_value\"], desc: true)\r\n  |> limit(n: ${limit})"
    }
   ]
  },
  {
   "title": "UPTIME ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "src1 = from(bucket: \"monitoring\")\r\n  |> range(start: -1m)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pc\" and r[\"_field\"] == \"uptime_minutes\")\r\n  |> group(columns: [\"host\"])\r\n  |> last()\r\n\r\nsrc2 = from(bucket: \"BucketMonitoring\")\r\n  |> range(start: -1m)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system\" and r[\"_field\"] == \"uptime_minutes\")\r\n  |> group(columns: [\"host\"])\r\n  |> last()\r\n\r\nunion(tables: [src1, src2])\r\n  |> group()\r\n  |> sort(columns: [\"_value\"], desc: true)\r\n  |> limit(n: ${limit})"
    }
   ]
  },
  {
   "title": "Read Bytes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "data = from(bucket: \"BucketMonitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r[\"_measurement\"] == \"diskio\" and\r\n    r[\"_field\"] == \"read_bytes_sec\"\r\n  )\r\n\r\ntop5 = data\r\n  |> range(start: -5m)\r\n  |> group(columns: [\"host\", \"device\"])\r\n  |> mean()\r\n  |> group()\r\n  |> sort(columns: [\"_value\"], desc: true)\r\n  |> limit(n: ${limit})\r\n  |> keep(columns: [\"host\", \"device\"])\r\n\r\njoin(tables: {d: data, t: top5}, on: [\"host\", \"device\"])\r\n  |> map(fn: (r) => ({ r with display_name: r.host + \" - \" + r.device }))\r\n  \r\n  |> pivot(rowKey:[\"_time\", \"host\"], columnKey: [\"display_name\"], valueColumn: \"_value\")"
    }
   ]
  },
  {
   "title": "Write Bytes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "data = from(bucket: \"BucketMonitoring\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r[\"_measurement\"] == \"diskio\" and\r\n    r[\"_field\"] == \"write_bytes_sec\"\r\n  )\r\n\r\ntop5 = data\r\n  |> range(start: -5m)\r\n  |> group(columns: [\"host\", \"device\"])\r\n  |> mean()\r\n  |> group()\r\n  |> sort(columns: [\"_value\"], desc: true)\r\n  |> limit(n: ${limit})\r\n  |> keep(columns: [\"host\", \"device\"])\r\n\r\njoin(tables: {d: data, t: top5}, on: [\"host\", \"device\"])\r\n  |> map(fn: (r) => ({ r with display_name: r.host + \" - \" + r.device }))\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"display_name\"], valueColumn: \"_value\")"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 30 },
   "options": {
    "content": "<div style=\"display: flex; justify-content: space-between; align-items: center;\">\n  <a href=\"/d/43cb4335-0db6-4be7-9ff4-cf3e7652570f/tableau-general\" style=\"background: #1f77b4; color: white; padding: 10px 20px; text-decoration: none; border-radius: 4px; display: inline-block;\">← Tableau Général</a>\n</div>"
   }
  }
 ]
}